SELECT DISTINCT ?legislature ?legislatureLabel ?adminArea ?adminAreaLabel ?adminAreaTypes ?legislaturePost ?legislaturePostLabel ?numberOfSeats WHERE {
  {
    SELECT DISTINCT ?adminArea
                (MIN(?primarySort) AS ?primarySort)
                (GROUP_CONCAT(DISTINCT REPLACE(STR(?adminAreaType), '^.*/', ''); SEPARATOR=" ") AS ?adminAreaTypes) {
  {
    VALUES (?adminArea ?primarySort ?adminAreaType) { (wd:Q145 1 wd:Q6256) }
  } UNION {
    # Find regional admin areas of this country (generally FLACSen)
    ?adminArea wdt:P17 wd:Q145 ;
          wdt:P31/wdt:P279* wd:Q10864048
    VALUES (?primarySort ?adminAreaType) { (2 wd:Q10864048) }
  } UNION {
    # Find cities or municipalities with populations of over 250k
    VALUES ?adminAreaType { wd:Q515 wd:Q15284 }
    ?adminArea wdt:P17 wd:Q145 ;
       wdt:P31/wdt:P279* ?adminAreaType ;
       wdt:P1082 ?population .
    FILTER (?population > 250000)
    VALUES ?primarySort { 3 }
  } UNION {
    VALUES (?adminArea ?primarySort ?adminAreaType) {
      (wd:Q1140130 4 wd:Q24238356)
      (wd:Q202088 4 wd:Q24238356)
      (wd:Q215038 4 wd:Q24238356)
      (wd:Q214162 4 wd:Q24238356)
      (wd:Q213560 4 wd:Q24238356)
      (wd:Q40608 4 wd:Q24238356)
      (wd:Q205679 4 wd:Q24238356)
      (wd:Q693450 4 wd:Q24238356)
      (wd:Q215030 4 wd:Q24238356)
      (wd:Q208955 4 wd:Q24238356)
      (wd:Q205690 4 wd:Q24238356)
      (wd:Q208152 4 wd:Q24238356)
      (wd:Q730706 4 wd:Q24238356)
      (wd:Q210563 4 wd:Q24238356)
      (wd:Q202059 4 wd:Q24238356)
      (wd:Q207201 4 wd:Q24238356)
      (wd:Q208201 4 wd:Q24238356)
      (wd:Q210531 4 wd:Q24238356)
      (wd:Q207218 4 wd:Q24238356)
      (wd:Q208139 4 wd:Q24238356)
      (wd:Q26888 4 wd:Q24238356)
      (wd:Q151048 4 wd:Q24238356)
      (wd:Q40478 4 wd:Q24238356)
      (wd:Q32504 4 wd:Q24238356)
      (wd:Q32515 4 wd:Q24238356)
      (wd:Q179351 4 wd:Q24238356)
      (wd:Q188801 4 wd:Q24238356)
      (wd:Q207208 4 wd:Q24238356)
      (wd:Q320378 4 wd:Q24238356)
      (wd:Q210476 4 wd:Q24238356)
      (wd:Q32508 4 wd:Q24238356)
      (wd:Q205817 4 wd:Q24238356)
      (wd:Q23311 4 wd:Q24238356)
      (wd:Q205358 4 wd:Q24238356)
      (wd:Q20986424 4 wd:Q24238356)
      (wd:Q774015 4 wd:Q24238356)
      (wd:Q1142118 4 wd:Q24238356)
      (wd:Q21885975 4 wd:Q24238356)
      (wd:Q1878732 4 wd:Q24238356)
      (wd:Q1280897 4 wd:Q24238356)
      (wd:Q21012735 4 wd:Q24238356)
      (wd:Q1925846 4 wd:Q24238356)
      (wd:Q20986417 4 wd:Q24238356)
      (wd:Q763171 4 wd:Q24238356)
      (wd:Q21665571 4 wd:Q24238356)
      (wd:Q21525592 4 wd:Q24238356)
      (wd:Q2834810 4 wd:Q24238356)
      (wd:Q12956644 4 wd:Q24238356)
      (wd:Q2379199 4 wd:Q24238356)
      (wd:Q55934339 4 wd:Q24238356)
      (wd:Q24342199 4 wd:Q24238356)
      (wd:Q21683230 4 wd:Q24238356)
      (wd:Q21891722 4 wd:Q24238356)
      (wd:Q21674890 4 wd:Q24238356)
      (wd:Q21885980 4 wd:Q24238356)
      (wd:Q21885987 4 wd:Q24238356)
      (wd:Q894090 4 wd:Q24238356)
      (wd:Q1022488 4 wd:Q24238356)
      (wd:Q21885994 4 wd:Q24238356)
      (wd:Q21683242 4 wd:Q24238356)
      (wd:Q21693433 4 wd:Q24238356)
    }
  }

  # Remove admin areas that have ended
  FILTER NOT EXISTS { ?adminArea wdt:P582|wdt:P576 ?adminAreaEnd . FILTER (?adminAreaEnd < NOW()) }
} GROUP BY ?adminArea ORDER BY ?primarySort ?adminArea

  }

  ?adminArea wdt:P194/wdt:P527? ?legislature .

  VALUES ?legislatureType { wd:Q11204 wd:Q10553309 }
  ?legislature wdt:P31/wdt:P279* ?legislatureType .
  FILTER (?legislatureType != wd:Q11204 || NOT EXISTS { ?legislature wdt:P527 ?legislaturePart . ?legislaturePart  wdt:P31/wdt:P279* wd:Q10553309 })

  # Attempt to find the position for members of the legislature
  OPTIONAL {
    # Both "has part" and "has parts of class" seem to be used; with the latter not in keeping with the draft model
    ?legislature wdt:P527|wdt:P2670 ?legislaturePost .
    ?legislaturePost wdt:P31/wdt:P279* wd:Q4164871 .
    # Make sure positions are either legislators or councillors (and so exclude e.g. mayors)
    FILTER EXISTS {
      VALUES ?legislaturePostSuperType { wd:Q4175034 wd:Q708492 }
      ?legislaturePost wdt:P279+ ?legislaturePostSuperType .
    }
  }
  OPTIONAL {
    ?legislature wdt:P1342 ?numberOfSeats .
  }

  # Remove legislatures that have ended
  FILTER NOT EXISTS { ?legislature wdt:P576 ?legislatureEnd . FILTER (?legislatureEnd < NOW()) }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,cy". }
} ORDER BY ?primarySort ?legislature ?legislaturePost
