SELECT DISTINCT
  ?house ?houseLabel
  ?legislature ?legislatureLabel
  ?term ?termLabel
  ?termStart ?termEnd
  ?termSpecificPosition
WHERE {
  VALUES (?house ?position) {
    (wd:Q11005 wd:Q16707842)
    (wd:Q11007 wd:Q18952564)
    (wd:Q206171 wd:Q1711695)
    (wd:Q285714 wd:Q3272410)
    (wd:Q493517 wd:Q3406079)
    (wd:Q55932205 rdf:nil)
    (wd:Q55934729 rdf:nil)
    (wd:Q55935300 rdf:nil)
    (wd:Q55935300 rdf:nil)
    (wd:Q56006891 rdf:nil)
    (wd:Q42609766 rdf:nil)
    (wd:Q55465119 wd:Q55372701)
    (wd:Q55932205 rdf:nil)
    (wd:Q55934204 rdf:nil)
    (wd:Q55934729 rdf:nil)
    (wd:Q55934865 rdf:nil)
    (wd:Q55935434 rdf:nil)
    (wd:Q55935459 rdf:nil)
    (wd:Q55935543 rdf:nil)
    (wd:Q55935708 rdf:nil)
    (wd:Q55936924 rdf:nil)
    (wd:Q55984160 rdf:nil)
    (wd:Q55984182 rdf:nil)
    (wd:Q55984301 rdf:nil)
    (wd:Q55984362 rdf:nil)
    (wd:Q55984451 rdf:nil)
    (wd:Q55984834 rdf:nil)
    (wd:Q55985891 rdf:nil)
    (wd:Q55985896 rdf:nil)
    (wd:Q55986002 rdf:nil)
    (wd:Q55986782 rdf:nil)
    (wd:Q55986971 rdf:nil)
    (wd:Q55987392 rdf:nil)
    (wd:Q55987515 rdf:nil)
    (wd:Q55988536 rdf:nil)
    (wd:Q55988698 rdf:nil)
    (wd:Q55989100 rdf:nil)
    (wd:Q55989252 rdf:nil)
    (wd:Q55989708 rdf:nil)
    (wd:Q55989961 rdf:nil)
    (wd:Q55990309 rdf:nil)
    (wd:Q56005992 rdf:nil)
    (wd:Q56006121 rdf:nil)
    (wd:Q56006212 rdf:nil)
    (wd:Q56006597 rdf:nil)
    (wd:Q56006976 rdf:nil)
    (wd:Q56007071 rdf:nil)
    (wd:Q56007345 rdf:nil)
    (wd:Q56007630 rdf:nil)
    (wd:Q56007676 rdf:nil)
    (wd:Q56007809 rdf:nil)
    (wd:Q56007943 rdf:nil)
    (wd:Q56007955 rdf:nil)
    (wd:Q56007976 rdf:nil)
    (wd:Q56008172 rdf:nil)
    (wd:Q56008431 rdf:nil)
    (wd:Q56008455 rdf:nil)
    (wd:Q56008458 rdf:nil)
    (wd:Q56008462 rdf:nil)
    (wd:Q56008464 rdf:nil)
    (wd:Q56008467 rdf:nil)
    (wd:Q56008473 rdf:nil)
    (wd:Q56008474 rdf:nil)
    (wd:Q56008475 rdf:nil)
    (wd:Q56008478 rdf:nil)
    (wd:Q56008483 rdf:nil)
    (wd:Q56008486 rdf:nil)
    (wd:Q56008490 rdf:nil)
    (wd:Q56008493 rdf:nil)
  }
  ?house (p:P361/ps:P361)* ?legislature .
      ?baseTerm p:P31|p:P279 [ ps:P279|ps:P31 wd:Q15238777 ; pq:P642 ?legislature ] .
      OPTIONAL { ?subTerm wdt:P31 ?baseTerm }

  BIND(COALESCE(?subTerm, ?baseTerm) AS ?term)

  OPTIONAL { ?term (wdt:P580|wdt:P571) ?termStart. }
  OPTIONAL { ?term (wdt:P582|wdt:P576) ?termEnd. }
  OPTIONAL { ?term (wdt:P155|wdt:P1365) ?termReplaces }
  OPTIONAL { ?term (wdt:P156|wdt:P1366) ?termReplacedBy }
  OPTIONAL {
    ?termSpecificPosition wdt:P31/wdt:P279* wd:Q4164871 ;
                          p:P279 [ ps:P279 ?position ;
                                   pq:P2937 ?term ] .
  }

  FILTER (!BOUND(?termEnd) || ?termEnd > NOW())
  FILTER (!BOUND(?termReplacedBy))
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,cy". }
} ORDER BY ?termStart ?term
